"""Emit Sources/PerthCoreML/PerthAssets.swift: the STFT window and the resampler FIR taps.

These are compiled into the library as base64 blobs rather than shipped as SPM resources --
no Bundle.module lookup to go wrong when the package is vendored into an app.

The STFT window MUST come from the checkpoint: Perth's AudioProcessor is an nn.Module, so
load_state_dict overwrites torchaudio's freshly-computed hann with the buffer stored in
perth_net_250000.pth.tar. The two differ by 1 ULP, which is visible in the output waveform.
"""
import base64
import sys
from pathlib import Path

import numpy as np
import torch
from scipy.signal import firwin

sys.path.insert(0, "/Users/ilia/Developer/Perth/src")
from perth.perth_net.perth_net_implicit.perth_watermarker import PerthImplicitWatermarker

from resampler_study import resample_poly_manual

DST = Path(__file__).parent.parent / "Sources/PerthCoreML/PerthAssets.swift"

# librosa's default res_type is soxr_hq, which we are not vendoring (LGPL). An 801-tap
# Kaiser(13.75) firwin at soxr's cutoff reproduces it to ~112 dB SNR -- versus only ~54 dB
# for scipy's resample_poly. Measured, not assumed.
SOXR_TAPS, SOXR_BETA, SOXR_CUTOFF = 801, 13.75, 11482 / 48000


def soxr_clone_meta(up, down):
    half = (SOXR_TAPS - 1) // 2
    h = (firwin(SOXR_TAPS, SOXR_CUTOFF, window=("kaiser", SOXR_BETA)) * up)
    n_pre_pad = down - half % down
    n_pre_remove = (half + n_pre_pad) // down
    taps = np.concatenate((np.zeros(n_pre_pad), h))
    return dict(up=up, down=down, n_pre_remove=int(n_pre_remove), taps=taps)


def b64(a: np.ndarray, dtype) -> str:
    return base64.b64encode(np.asarray(a, dtype=dtype).tobytes()).decode()


def main():
    net = PerthImplicitWatermarker(device="cpu").perth_net
    window = net.ap.spectrogram.window.detach().cpu().numpy()
    assert window.shape == (2048,) and window.dtype == np.float32

    # detect path: librosa res_type="polyphase" == scipy resample_poly
    _, up = resample_poly_manual(np.zeros(64), 4, 3)     # 24 kHz -> 32 kHz
    _, dn = resample_poly_manual(np.zeros(64), 3, 4)     # 32 kHz -> 24 kHz
    # apply path: librosa default == soxr_hq
    hq_up = soxr_clone_meta(4, 3)
    hq_dn = soxr_clone_meta(3, 4)

    src = f'''// Generated by converter/gen_swift_assets.py -- do not edit.
import Foundation

/// Constants baked out of the Perth checkpoint and out of scipy's filter design.
enum PerthAssets {{

    /// The 2048-tap STFT window, taken from `ap.spectrogram.window` in
    /// `perth_net_250000.pth.tar` -- NOT a freshly computed `hann_window(2048)`.
    ///
    /// Perth's `AudioProcessor` is an `nn.Module`, so the window is a registered buffer and
    /// `load_state_dict` overwrites torchaudio's default with whatever the checkpoint stored.
    /// The stored window differs from today's `torch.hann_window(2048)` by one ULP
    /// (5.96e-08), and that difference propagates all the way to the output waveform -- it
    /// puts a ~2e-7 floor under every comparison against Python until you use this one.
    static let stftWindow: [Float] = decodeF32("{b64(window, np.float32)}")

    // -- Detect path -------------------------------------------------------------------
    // `get_watermark` resamples with librosa `res_type="polyphase"` == scipy resample_poly.
    // The detect path MUST use these and not the HQ pair: the HQ filter's different stopband
    // shifts the magmask threshold (the dB transform amplifies it across all 1025 bins) and
    // flips mask bits, and the gate is "our detector agrees with Python's".
    //
    // Taps are already scaled by `up` and zero-padded exactly as scipy does, so plain upfirdn
    // plus a trim of `preRemove` reproduces scipy (verified: max|d| 1.8e-07).

    /// scipy `resample_poly(x, up: 4, down: 3)` -- 24 kHz to 32 kHz.
    static let polyUp24to32 = PolyphaseTaps(
        up: {up['up']}, down: {up['down']}, preRemove: {up['n_pre_remove']},
        taps: decodeF64("{b64(up['taps'], np.float64)}"))

    /// scipy `resample_poly(x, up: 3, down: 4)` -- 32 kHz back to 24 kHz.
    static let polyDown32to24 = PolyphaseTaps(
        up: {dn['up']}, down: {dn['down']}, preRemove: {dn['n_pre_remove']},
        taps: decodeF64("{b64(dn['taps'], np.float64)}"))

    // -- Apply path --------------------------------------------------------------------
    // `apply_watermark` resamples with librosa's DEFAULT res_type, which is soxr_hq. We do
    // not vendor libsoxr (LGPL); an {SOXR_TAPS}-tap Kaiser({SOXR_BETA}) firwin at soxr's cutoff
    // reproduces it to ~112 dB SNR, versus ~54 dB for resample_poly. Measured on real speech.

    /// soxr_hq-equivalent, 24 kHz to 32 kHz.
    static let hqUp24to32 = PolyphaseTaps(
        up: {hq_up['up']}, down: {hq_up['down']}, preRemove: {hq_up['n_pre_remove']},
        taps: decodeF64("{b64(hq_up['taps'], np.float64)}"))

    /// soxr_hq-equivalent, 32 kHz back to 24 kHz.
    static let hqDown32to24 = PolyphaseTaps(
        up: {hq_dn['up']}, down: {hq_dn['down']}, preRemove: {hq_dn['n_pre_remove']},
        taps: decodeF64("{b64(hq_dn['taps'], np.float64)}"))

    private static func decodeF32(_ s: String) -> [Float] {{
        let d = Data(base64Encoded: s)!
        return d.withUnsafeBytes {{ Array($0.bindMemory(to: Float.self)) }}
    }}

    private static func decodeF64(_ s: String) -> [Double] {{
        let d = Data(base64Encoded: s)!
        return d.withUnsafeBytes {{ Array($0.bindMemory(to: Double.self)) }}
    }}
}}

/// A polyphase FIR resampling stage, as designed by `scipy.signal.resample_poly`.
struct PolyphaseTaps {{
    let up: Int
    let down: Int
    /// How many leading output samples scipy discards to undo the filter's group delay.
    let preRemove: Int
    let taps: [Double]
}}
'''
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(src)
    print(f"wrote {DST}")
    print(f"  window          {len(window):4d} taps")
    for label, meta in (("poly up   4/3", up), ("poly down 3/4", dn),
                        ("hq   up   4/3", hq_up), ("hq   down 3/4", hq_dn)):
        print(f"  {label}   {len(meta['taps']):4d} taps, preRemove={meta['n_pre_remove']}")


if __name__ == "__main__":
    main()
